title:              The S&M Foote Family Letters
email:              matthew.foote@gmail.com
description:        Family letters about the exploits and travails of the Sarah and Matthew Foote Family
author:             Mostly Matthew
baseurl:            "/blog"
url:                "https://msfoote.github.io"

# Social Profiles
twitter_username:   
github_username:    msfoote
facebook_username:  matthew.d.foote
instagram_username:  
linkedin_username:  matthewdfoote

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
